### ISSUE TITLE
VC activity bug

### ISSUE THREAD

**Issue by RealYusufIsmail** [Together-Java/TJ-Bot#272] opened 2021-11-19 20:44 UTC
**Describe the bug**

When i ran the command `/vc-activity application application:YouTube Together max-uses:1 max-age:1 ` it run an into an error saying YouTube Together is an invalid choices.

**Expected behavior**
To recognise YouTube Together and send a link

**Screenshots**
<img width="861" alt="Screenshot 2021-11-19 at 20 44 04" src="https://user-images.githubusercontent.com/67903886/142689345-c545d38d-27c3-443b-b471-b504d55f9983.png">

**Comment by Tais993** [comment] 2021-11-19 20:52
You didn't set the application, read the error Discord gives you.

There's a space between `application:` and `YouTube Together`

**Comment by RealYusufIsmail** [comment] 2021-11-19 21:05
Issues is not fixed

**Comment by RealYusufIsmail** [comment] 2021-11-19 21:06
https://user-images.githubusercontent.com/67903886/142691609-41277cc1-146a-453d-bde2-60b5ae6881bf.mp4

**Comment by Tais993** [comment] 2021-11-19 21:08
Is issue on Discords end then, will try to reproduce

**Comment by RealYusufIsmail** [comment] 2021-11-19 21:11
ok

**Comment by Tais993** [comment] 2021-11-20 13:28
Can reproduce in our TJ server with the official bot.

Can't reproduce with the same code on other servers, so can't fix.

**Comment by Tais993** [comment] 2021-11-20 14:12
Could try to remove all spaces in the choices, maybe that works?
Thus `YouTube Together` becomes `YouTube_Together`

**Comment by Zabuzard** [comment] 2021-11-22 08:28
> Could try to remove all spaces in the choices, maybe that works? Thus `YouTube Together` becomes `YouTube_Together`

I noticed a similar issue with another command. Basically, you have to enter the command either by clicking the buttons and items in the UI or by hitting TAB. But copy&paste'ing the text wont recognize it correctly.

In any case, it is not a bug on our end. I am closing this as **wontfix**. That said, it is good to be aware of this issue and actively design stuff in a way that it does not unecessarily run into this problem.

@Tais993 Feel free to create a GH issue to remove the spaces in the command, low priority and "good first issue", I guess 👍

**Closed by Zabuzard** 2021-11-22 08:28 UTC
Labels: bug, wontfix, priority: normal
