### ISSUE TITLE
make Help System use discord threads

### ISSUE THREAD

**Issue by borgrel** [Together-Java/TJ-Bot#306] opened 2021-12-07 10:24 UTC
**Is your feature request related to a problem? Please describe.**

- Lots of help requests are lost when help requests 'time out' after an hour (especially the more technical / difficult (not amateur) questions.
- Often there are not enough channels for the volume of help requests recieved
- Often the current channel breakup (6 channels for basic java, 3 channels for frameworks, 2 channels for swing/javaFX, etc) is incorrect for current needs

**Describe the solution you'd like**
Enhance the existing Help System to use threads:
- Instead of a status showing busy/free channels change the status display to show open help requests (linked to the relevant thread) which are tagged to show the relevant experince needed to answer the questions. Some example tags would be: `Mooc`, `Spring Boot`, `Spring`,  `JDBC`, `MongoDb`, `MySQL`, `swing`, `javaFX` etc
- Create a 'form' for users to use to open a thread and ask their question (this will prevent spamming channels / spamming new thread creations, allow the system to monitor existing channels, etc)
- Allow top helpers (current and previous) / Moderators and maybe other roles to add tags, modify title, etc for help requests
- Allow others to try change title, tags etc of the request but only with the OP's confirmation

**Comment by borgrel** [comment] 2021-12-07 10:26
we need a clear and well defined brief about what is required from the threaded help system
what does everybody expect me to build

**Comment by Tais993** [comment] 2021-12-07 10:54
It was my idea to wait till forms get added.
![image](https://user-images.githubusercontent.com/49957334/145015503-7e56e956-c4a4-42fd-a13b-1b0c509746d7.png)

We can use this so the user presses a button / runs a command.
After the interaction we can show such a form.

Where we'd show something in the lines of
> What is your question/issue in 1 line? a text input field
> What is your full; question/issue? a text input field
> Select all the relating tags: selectionmenu
> What's the relating code? a text input field

The bot creates a thread where the name is `status • short question • tag, tag, tag`

This allows helpers to search for certain tags
![image](https://user-images.githubusercontent.com/49957334/145016114-21c3bf18-f5fc-4145-a2c5-4ec51292f61b.png)

The bot proceeds to send the full question with the code in a codeblock.



Not sure what others think about this idea, since it means we'll have to wait. (How long, I don't know)
But I do think it'd be the best UX wise

**Comment by Zabuzard** [comment] 2021-12-07 11:09
forms seem to be ideal for this. any rough ETA on that?

**Comment by Zabuzard** [comment] 2022-05-20 16:38
Duplicate of #444

**Closed by Zabuzard** 2022-05-20 16:38 UTC
Labels: enhancement, priority: major
